# Generated by Django 5.2 on 2026-04-07 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minibiblio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImatgeLlibre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imatge', models.ImageField(upload_to='llibres/galeria/')),
                ('descripcio', models.CharField(blank=True, max_length=100, null=True)),
                ('llibre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='minibiblio.llibre')),
            ],
        ),
    ]
